export const PREDEFINED_ICONS = [
    "icon-phone",
    "icon-cart",
    "icon-compare",
    "icon-cancel",
    "icon-lock",
    "icon-post",
    "icon-clock",
    "icon-support",
    "icon-chat",
    "icon-cog",
    "icon-wrench",
    "icon-money",
    "icon-bitcoin",
    "icon-ok",
    "icon-truck",
    "icon-info",
    "icon-online-support",
    "icon-shipping",
    "icon-credit-card",
    "icon-category-motors",
    "icon-category-electronics",
    "icon-category-mechanics",
    "icon-category-motorcycles",
    "icon-category-steering",
    "icon-category-fluids",
    "icon-category-chains",
    "icon-category-pedals",
    "icon-category-saddle",
    "icon-category-tools",
    "icon-secure-payment",    
]

export const PREDEFINED_TYPES = [
    "brands",
    "categories",
    "tags",
]